name: cm_cmp_sdk_v3
description: "The CMP Plugin allows you to integrate Consent Management functionality."
version: 3.2.0
homepage: "https://www.consentmanager.net"

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: net.consentmanager.cm_cmp_sdk_v3
        pluginClass: CmpSdkPlugin
      ios:
        pluginClass: CmpSdkPlugin
